-- ============================================================================
-- eRPH · MIGRATION 001b — the schema delta (paste this whole file)
-- ============================================================================
-- Run AFTER 001a_alter_types.sql, which must be run one line at a time.
--
-- For a Supabase project created before commit e46e870. A fresh install needs
-- none of this: db/schema.sql already describes the end state.
--
-- Generated by scripts/gen-migration.py from db/schema.sql, so the definitions
-- below cannot drift from the schema they are migrating towards.
--
--   python scripts/gen-migration.py
-- ============================================================================

-- ── 1 · column defaults ────────────────────────────────────────────────────
alter table erph.user         alter column role set default 'guru_biasa';
alter table erph.school_member alter column role set default 'guru_biasa';

-- ── 2 · the single-stage reviewer is gone ──────────────────────────────────
drop function if exists erph.review_rph(uuid, smallint, text);

-- ── 3 · helpers, RPCs and the new admin set-up ─────────────────────────────
-- Shapes that changed: these cannot be `create or replace`d over.
drop function if exists erph.admin_list_members(uuid);
drop function if exists erph.admin_set_setting(uuid, smallint, time, boolean);


create or replace function erph.is_staff(p_school uuid)
returns boolean language sql stable security definer set search_path = erph, public as $$
  select exists (select 1 from erph.school_member
                 where user_id = erph.actor() and school_id = p_school
                   and role in ('gpk','guru_besar') and is_active);
$$;


create or replace function erph.shares_school_with(p_user uuid)
returns boolean language sql stable security definer set search_path = erph, public as $$
  select exists (
    select 1
    from erph.school_member a
    join erph.school_member b on a.school_id = b.school_id
    where a.user_id = erph.actor() and a.is_active
      and a.role in ('gpk','guru_besar')
      and b.user_id = p_user and b.is_active);
$$;


create or replace function erph.submit_rph(p_document uuid, p_force boolean default false)
returns jsonb language plpgsql security definer set search_path = erph, public as $$
declare
  v_doc erph.rph_document%rowtype;
  v_pct smallint;
begin
  perform set_config('app.rpc', '1', true);              -- unlocks guard_review_fields

  select * into v_doc from erph.rph_document
   where id = p_document and deleted_at is null for update;
  if not found then raise exception 'RPH tidak dijumpai'; end if;

  -- NULL-actor guard, matching sync_rph's.
  --
  -- This is load-bearing: `owner_id <> erph.actor()` evaluates to NULL when no
  -- actor can be resolved, and PL/pgSQL treats NULL in IF as false — so the
  -- "Tidak dibenarkan" branch would be skipped and ANY caller (including one with
  -- just the publishable key, for whom actor() is always null) could submit
  -- another teacher's plan. `IS DISTINCT FROM` never yields NULL.
  if erph.actor() is null then
    raise exception 'Belum log masuk';
  end if;

  -- owner OR staff (a GPK or Guru Besar may resubmit on the teacher's behalf)
  if v_doc.owner_id is distinct from erph.actor()
     and not erph.has_role(v_doc.school_id, array['gpk','guru_besar']::erph.member_role[])
  then raise exception 'Tidak dibenarkan'; end if;
  if v_doc.status = 'approved' then raise exception 'Telah disahkan lengkap'; end if;
  -- With the Guru Besar already: only the reviewer rung may move it from here.
  if v_doc.status = 'forwarded' then raise exception 'Sedang dalam kelulusan Guru Besar'; end if;

  v_pct := erph.rph_completeness(v_doc.payload);
  if v_pct < 100 and not p_force then
    return jsonb_build_object('ok', false, 'completeness', v_pct,
      'error', 'Refleksi/Intervensi belum lengkap');
  end if;

  update erph.rph_document
     set status = 'submitted', submitted_at = now(),
         grade = null, reviewed_by = null, reviewed_at = null,
         version = version + 1, client_updated_at = now()
   where id = p_document
  returning * into v_doc;

  insert into erph.rph_revision (document_id, version, payload, completeness, actor_id, reason)
  values (v_doc.id, v_doc.version, v_doc.payload, v_pct, erph.actor(), 'resubmit')
  on conflict (document_id, version) do nothing;

  insert into erph.audit_log (school_id, actor_id, entity, entity_id, action, after)
  values (v_doc.school_id, erph.actor(), 'rph_document', v_doc.id, 'submit',
          jsonb_build_object('completeness', v_pct, 'status', 'submitted'));

  return jsonb_build_object('ok', true, 'status', 'submitted', 'completeness', v_pct,
                            'version', v_doc.version);
end $$;


create or replace function erph.school_week_stats(p_school uuid, p_session text, p_week smallint)
returns table (expected int, submitted int, approved int, returned_t int,
               drafts int, compliance numeric)
language plpgsql stable security definer set search_path = erph, public as $$
begin
  -- Any member: this returns counts and a percentage and never a name, so a
  -- Guru Biasa can see how the school is doing without seeing who is behind
  -- it. The per-teacher view lives behind `pantau` and is not served here.
  if not erph.is_member(p_school) and not erph.is_staff(p_school) then
    raise exception 'Tidak dibenarkan';
  end if;
  return query
  with t as (
    select count(*)::int n from erph.school_member
     where school_id = p_school and role = 'guru_biasa' and is_active
  ), d as (
    select status, grade from erph.rph_document
     where school_id = p_school and session = p_session
       and week_no = p_week and deleted_at is null
  )
  select
    (select n from t),
    (select count(*)::int from d where status <> 'draft'),
    (select count(*)::int from d where grade = 1),
    (select count(*)::int from d where status = 'returned' or grade = 0),
    (select count(*)::int from d where status = 'draft'),
    round(100.0 * coalesce((select count(*) from d where grade = 1), 0)
          / nullif((select n from t), 0), 1);
end $$;


create or replace function erph.admin_set_member(p_school uuid, p_user uuid,
                                                 p_role erph.member_role,
                                                 p_active boolean)
returns void language plpgsql security definer set search_path = erph, public as $$
begin
  if not erph.has_role(p_school, array['pentadbir']::erph.member_role[]) then
    raise exception 'Peranan pentadbir diperlukan';
  end if;
  if p_role = 'system' then
    raise exception 'Peranan sistem tidak boleh diberikan kepada akaun';
  end if;
  if not exists (select 1 from erph.school_member
                 where school_id = p_school and user_id = p_user) then
    raise exception 'Akaun bukan ahli sekolah ini';
  end if;
  update erph.school_member set role = p_role
   where school_id = p_school and user_id = p_user;
  update erph.user set is_active = p_active where id = p_user;
end $$;


create or replace function erph.admin_set_setting(p_school uuid, p_weekday smallint,
                                                  p_time time,
                                                  p_require_complete boolean,
                                                  p_session text default null)
returns void language plpgsql security definer set search_path = erph, public as $$
begin
  if not erph.has_role(p_school, array['pentadbir']::erph.member_role[]) then
    raise exception 'Peranan pentadbir diperlukan';
  end if;
  if p_weekday not between 1 and 7 then raise exception 'Hari mesti antara 1 dan 7'; end if;
  if p_session is not null and p_session !~ '^[0-9]{4}/[0-9]{4}$' then
    raise exception 'Sesi mesti dalam bentuk TTTT/TTTT';
  end if;
  update erph.school_setting
     set submit_weekday = p_weekday,
         submit_time = p_time,
         require_complete = p_require_complete,
         current_session = coalesce(p_session, current_session)
   where school_id = p_school;
end $$;

-- ── 4 · policies embedding a role literal ─────────────────────────────────
drop policy if exists rph_reviewer_read on erph.rph_document;
drop policy if exists rph_revision_read on erph.rph_revision;
drop policy if exists rph_review_read on erph.rph_review;
drop policy if exists export_read on erph.export_file;
drop policy if exists audit_admin_read on erph.audit_log;
drop policy if exists storage_read on storage.objects;

create policy export_read on erph.export_file
  for select using (
    created_by = erph.actor()
    or exists (select 1 from erph.rph_document d where d.id = erph.export_file.document_id
                 and (d.owner_id = erph.actor()
                      or erph.has_role(d.school_id, array['guru_besar','gpk']::erph.member_role[])))
  );

create policy audit_admin_read on erph.audit_log
  for select using (erph.has_role(erph.audit_log.school_id, array['guru_besar','gpk']::erph.member_role[]));

create policy storage_read on storage.objects
  for select to authenticated using (
       (bucket_id = 'rph-exports'
        and exists (select 1 from erph.rph_document d
                     where d.id::text = (storage.foldername(name))[1]
                       and (d.owner_id = erph.actor()
                            or erph.has_role(d.school_id, array['guru_besar','gpk']::erph.member_role[]))))
    or (bucket_id = 'attachments'
        and (storage.foldername(name))[1] = erph.actor()::text)
  );

-- ── 5 · views (keyed on status, so a GPK's grade-1 is not an approval) ─────
drop view if exists erph.v_teacher_week;
drop view if exists erph.v_school_compliance;

create view erph.v_teacher_week
with (security_invoker = true) as
select d.school_id, d.owner_id, d.session, d.week_no,
       count(*) filter (where d.status = 'draft')     as drafts,
       count(*) filter (where d.status in ('submitted','forwarded')) as submitted,
       count(*) filter (where d.status = 'approved')  as approved,
       count(*) filter (where d.status = 'returned')  as returned,
       round(avg(d.completeness), 1)                  as avg_completeness
from erph.rph_document d
where d.deleted_at is null
group by 1,2,3,4;

create view erph.v_school_compliance
with (security_invoker = true) as
select d.school_id, d.session, d.week_no,
       count(*)                                as total_docs,
       count(*) filter (where d.status = 'approved')                as approved,
       count(*) filter (where d.status = 'returned')                as rejected,
       count(*) filter (where d.status in ('submitted','forwarded')) as pending,
       round(100.0 * count(*) filter (where d.status = 'approved')
             / nullif(count(distinct d.owner_id), 0), 1) as compliance_pct
from erph.rph_document d
where d.deleted_at is null
group by 1,2,3;

-- ── 6 · accounts ───────────────────────────────────────────────────────────
-- The district/state roles are gone from the app. Postgres cannot drop an enum
-- value at all, so deleting the rows is what keeps the data honest — leaving
-- them would mean two roles nothing references.
-- If those accounts ever produced an export, delete its export_file rows first.
delete from erph.school_member where user_id in
  (select id from erph.user where username in ('ppd.petaling', 'jpn.selangor'));
delete from erph.user where username in ('ppd.petaling', 'jpn.selangor');

-- ── 7 · the Administrator account ──────────────────────────────────────────
-- From db/seed.sql; change the password hash before any real deployment.
insert into erph.user (username, password_hash, full_name, email, role, is_active)
values ('pentadbir.sk',
        'scrypt$16384$8$1$sBZJbXJZGtDoXYVtM_r_MA$_Q_vvOJhHbPEbvKonOnd-ktpbXbn0axcvfihN6Gvw3QbzfzfEWoXvyhHi8rFcWaxKqNtYn9iUxIlQYOTgGmVGg',
        'Pentadbir eRPH', 'pentadbir@sk0000.local', 'pentadbir', true)
on conflict do nothing;

insert into erph.school_member (school_id, user_id, role)
select s.id, u.id, 'pentadbir' from erph.school s, erph.user u
where s.kod_sekolah = 'SK0000' and u.username = 'pentadbir.sk'
on conflict do nothing;
