-- ============================================================================
-- eRPH · MIGRATION 002 — the administrator's set-up console
-- ============================================================================
-- Run AFTER 001a/001b. Safe to run more than once.
--
-- Adds the accounts, classes, subjects and session management behind
-- /pentadbiran, and the index that makes "create account" actually safe.
--
-- Two existing functions are dropped first rather than replaced: one changed
-- its return type (which `create or replace` refuses outright) and one gained a
-- parameter (which it would otherwise leave behind as an overload — the old
-- four-argument form would keep silently ignoring the new session argument).
--
-- Generated by scripts/gen-migration.py from db/schema.sql:
--
--   python scripts/gen-migration.py
--
-- ── 1 · shapes that changed ────────────────────────────────────────────────
drop function if exists erph.admin_list_members(uuid);
drop function if exists erph.admin_set_setting(uuid, smallint, time, boolean);

-- ── 2 · admin set-up functions ─────────────────────────────────────────────

create or replace function erph.admin_list_members(p_school uuid)
returns table (user_id uuid, username text, full_name text, email text,
               role erph.member_role, is_active boolean,
               last_login_at timestamptz, locked_until timestamptz,
               failed_logins int, password_changed_at timestamptz)
language sql stable security definer set search_path = erph, public as $$
  select m.user_id, u.username, u.full_name, u.email, m.role, u.is_active,
         u.last_login_at, u.locked_until, u.failed_logins, u.password_changed_at
    from erph.school_member m
    join erph.user u on u.id = m.user_id
   where m.school_id = p_school and erph.has_role(p_school, array['pentadbir']::erph.member_role[])
   order by m.role, u.username;
$$;


create or replace function erph.admin_create_member(p_school uuid, p_username text,
                                                    p_full_name text,
                                                    p_role erph.member_role,
                                                    p_password_hash text,
                                                    p_email text default null)
returns uuid language plpgsql security definer set search_path = erph, public as $$
declare
  v_id uuid;
  -- Login matches case-insensitively (`.ilike` in /api/auth/login), so the
  -- name is normalized here too: `GURU.BARU` must land on the "already used"
  -- check, not bounce off a format rule that rejects capitals the login
  -- screen would have accepted.
  v_username text := lower(trim(p_username));
begin
  if not erph.has_role(p_school, array['pentadbir']::erph.member_role[]) then
    raise exception 'Peranan pentadbir diperlukan';
  end if;
  if p_role = 'system' then
    raise exception 'Peranan sistem tidak boleh diberikan kepada akaun';
  end if;
  if v_username !~ '^[a-z0-9._-]{3,32}$' then
    raise exception 'Nama pengguna: 3-32 aksara, huruf kecil, nombor, titik atau tanda hubung';
  end if;
  if nullif(trim(p_full_name), '') is null then
    raise exception 'Nama penuh diperlukan';
  end if;
  if p_password_hash is null or length(p_password_hash) < 20 then
    raise exception 'Kata laluan tidak sah';
  end if;
  -- Race backstop for the app-side check: `user_username_uniq` is what actually
  -- makes this hold when two tabs submit the same name at once.
  if exists (select 1 from erph.user u where lower(u.username) = v_username) then
    raise exception 'Nama pengguna ini telah digunakan';
  end if;

  insert into erph.user (username, password_hash, full_name, email, role)
  values (v_username, p_password_hash, trim(p_full_name),
          nullif(trim(p_email), ''), p_role)
  returning id into v_id;

  insert into erph.school_member (school_id, user_id, role)
  values (p_school, v_id, p_role);

  return v_id;
end $$;


create or replace function erph.admin_reset_password(p_school uuid, p_user uuid,
                                                     p_password_hash text)
returns void language plpgsql security definer set search_path = erph, public as $$
begin
  if not erph.has_role(p_school, array['pentadbir']::erph.member_role[]) then
    raise exception 'Peranan pentadbir diperlukan';
  end if;
  if not exists (select 1 from erph.school_member
                 where school_id = p_school and user_id = p_user) then
    raise exception 'Akaun bukan ahli sekolah ini';
  end if;
  if p_password_hash is null or length(p_password_hash) < 20 then
    raise exception 'Kata laluan tidak sah';
  end if;

  update erph.user
     set password_hash = p_password_hash,
         password_changed_at = now(),
         failed_logins = 0,
         locked_until = null
   where id = p_user;
end $$;


create or replace function erph.admin_unlock_member(p_school uuid, p_user uuid)
returns void language plpgsql security definer set search_path = erph, public as $$
begin
  if not erph.has_role(p_school, array['pentadbir']::erph.member_role[]) then
    raise exception 'Peranan pentadbir diperlukan';
  end if;
  if not exists (select 1 from erph.school_member
                 where school_id = p_school and user_id = p_user) then
    raise exception 'Akaun bukan ahli sekolah ini';
  end if;

  update erph.user set failed_logins = 0, locked_until = null where id = p_user;
end $$;


create or replace function erph.admin_set_member(p_school uuid, p_user uuid,
                                                 p_role erph.member_role,
                                                 p_active boolean)
returns void language plpgsql security definer set search_path = erph, public as $$
begin
  if not erph.has_role(p_school, array['pentadbir']::erph.member_role[]) then
    raise exception 'Peranan pentadbir diperlukan';
  end if;
  if p_role = 'system' then
    raise exception 'Peranan sistem tidak boleh diberikan kepada akaun';
  end if;
  if not exists (select 1 from erph.school_member
                 where school_id = p_school and user_id = p_user) then
    raise exception 'Akaun bukan ahli sekolah ini';
  end if;
  update erph.school_member set role = p_role
   where school_id = p_school and user_id = p_user;
  update erph.user set is_active = p_active where id = p_user;
end $$;


create or replace function erph.admin_list_classes(p_school uuid, p_session text)
returns table (id uuid, nama text, tahun smallint, tingkatan smallint,
               is_active boolean, doc_count bigint)
language sql stable security definer set search_path = erph, public as $$
  select c.id, c.nama, c.tahun, c.tingkatan, c.is_active,
         (select count(*) from erph.rph_document d
           where d.class_id = c.id and d.deleted_at is null)
    from erph.class c
   where c.school_id = p_school and c.session = p_session
     and erph.has_role(p_school, array['pentadbir']::erph.member_role[])
   order by c.is_active desc, c.nama;
$$;


create or replace function erph.admin_set_class(p_school uuid, p_id uuid,
                                                p_nama text, p_tahun smallint,
                                                p_session text, p_active boolean)
returns uuid language plpgsql security definer set search_path = erph, public as $$
declare
  v_id uuid := p_id;
begin
  if not erph.has_role(p_school, array['pentadbir']::erph.member_role[]) then
    raise exception 'Peranan pentadbir diperlukan';
  end if;
  if p_session !~ '^[0-9]{4}/[0-9]{4}$' then
    raise exception 'Sesi mesti dalam bentuk TTTT/TTTT';
  end if;
  if nullif(trim(p_nama), '') is null then
    raise exception 'Nama kelas diperlukan';
  end if;
  if p_tahun is not null and p_tahun not between 1 and 6 then
    raise exception 'Tahun mesti antara 1 dan 6';
  end if;

  if v_id is null then
    begin
      insert into erph.class (school_id, nama, tahun, session, is_active)
      values (p_school, trim(p_nama), p_tahun, p_session, coalesce(p_active, true))
      returning id into v_id;
    exception when unique_violation then
      raise exception 'Kelas "%s" sudah wujud dalam sesi ini', trim(p_nama);
    end;
  else
    -- Renaming onto a neighbour trips the same unique constraint, and swallowing
    -- it would report success while the name stayed put.
    begin
      update erph.class
         set nama = trim(p_nama),
             tahun = coalesce(p_tahun, tahun),
             is_active = coalesce(p_active, is_active)
       where id = v_id and school_id = p_school
      returning id into v_id;
    exception when unique_violation then
      raise exception 'Kelas "%s" sudah wujud dalam sesi ini', trim(p_nama);
    end;
    if v_id is null then
      raise exception 'Kelas tidak dijumpai';
    end if;
  end if;

  return v_id;
end $$;


create or replace function erph.admin_list_subjects(p_school uuid)
returns table (code text, nama text, curriculum erph.curriculum,
               is_active boolean, doc_count bigint)
language sql stable security definer set search_path = erph, public as $$
  select s.code, s.nama, s.curriculum, s.is_active,
         (select count(*) from erph.rph_document d
           where d.subject_code = s.code and d.deleted_at is null)
    from erph.subject s
   where erph.has_role(p_school, array['pentadbir']::erph.member_role[])
   order by s.curriculum, s.nama;
$$;


create or replace function erph.admin_set_subject(p_school uuid, p_code text,
                                                  p_active boolean)
returns void language plpgsql security definer set search_path = erph, public as $$
begin
  if not erph.has_role(p_school, array['pentadbir']::erph.member_role[]) then
    raise exception 'Peranan pentadbir diperlukan';
  end if;
  if not exists (select 1 from erph.subject where code = p_code) then
    raise exception 'Mata pelajaran tidak dijumpai';
  end if;

  update erph.subject set is_active = p_active where code = p_code;
end $$;


create or replace function erph.admin_create_subject(p_school uuid, p_code text,
                                                     p_nama text,
                                                     p_curriculum erph.curriculum)
returns void language plpgsql security definer set search_path = erph, public as $$
begin
  if not erph.has_role(p_school, array['pentadbir']::erph.member_role[]) then
    raise exception 'Peranan pentadbir diperlukan';
  end if;
  if p_code !~ '^[A-Z0-9]{2,12}$' then
    raise exception 'Kod subjek: 2-12 aksara huruf besar atau nombor';
  end if;
  if nullif(trim(p_nama), '') is null then
    raise exception 'Nama mata pelajaran diperlukan';
  end if;
  if exists (select 1 from erph.subject where code = p_code) then
    raise exception 'Kod subjek ini telah digunakan';
  end if;

  insert into erph.subject (code, nama, curriculum, is_active)
  values (p_code, trim(p_nama), p_curriculum, true);
end $$;


create or replace function erph.admin_set_setting(p_school uuid, p_weekday smallint,
                                                  p_time time,
                                                  p_require_complete boolean,
                                                  p_session text default null)
returns void language plpgsql security definer set search_path = erph, public as $$
begin
  if not erph.has_role(p_school, array['pentadbir']::erph.member_role[]) then
    raise exception 'Peranan pentadbir diperlukan';
  end if;
  if p_weekday not between 1 and 7 then raise exception 'Hari mesti antara 1 dan 7'; end if;
  if p_session is not null and p_session !~ '^[0-9]{4}/[0-9]{4}$' then
    raise exception 'Sesi mesti dalam bentuk TTTT/TTTT';
  end if;
  update erph.school_setting
     set submit_weekday = p_weekday,
         submit_time = p_time,
         require_complete = p_require_complete,
         current_session = coalesce(p_session, current_session)
   where school_id = p_school;
end $$;

-- ── 3 · username uniqueness ────────────────────────────────────────────────
-- Login matches case-insensitively and /api/admin/accounts creates accounts
-- from a form, so uniqueness has to hold on the lowercased name: `Admin` and
-- `admin` are the same person. Without it two accounts can share a username and
-- login picks one arbitrarily.
--
-- If this statement fails with "duplicate key", find the offenders first:
--
--   select lower(username), count(*) from erph.user
--    group by 1 having count(*) > 1;
--
-- resolve them, then re-run.
create unique index if not exists user_username_uniq on erph.user (lower(username));
