-- ============================================================================
-- eRPH · MIGRATION 003 — the school's own identity
-- ============================================================================
-- Run AFTER 001a/001b and 002. Safe to run more than once.
--
--   · erph.school gains `motto` and `logo_url` — what the administrator edits
--     from /pentadbiran and what the login screen, sidebar and printed RPH
--     then show everywhere.
--   · erph.admin_set_school writes those *and* `kod_sekolah`, which became
--     editable in the same release (see the comment on the function).
--   · the public `school-assets` bucket the crest is served from.
--   · profile_read / member_read stop a GPK or Guru Besar reading the
--     Administrator's account through `shares_school_with` / `is_staff`.
--
-- Policies are dropped first: `create policy` has no `if exists`, and these
-- two would otherwise collide with the copies already installed.
--
-- Generated by scripts/gen-migration.py from db/schema.sql:
--
--   python scripts/gen-migration.py
--
-- ── 1 · columns ─────────────────────────────────────────────────────────────
alter table erph.school add column if not exists motto text;
alter table erph.school add column if not exists logo_url text;

-- ── 2 · the bucket the crest is served from ─────────────────────────────────
-- Public: the crest renders on the login screen before a session exists.
insert into storage.buckets (id, name, public) values
  ('rph-exports', 'rph-exports', false),
  ('attachments', 'attachments', false),
  -- Public: the school crest renders on the login screen before any session
  -- exists, and `next/image` fetches it server-side without a cookie.
  ('school-assets', 'school-assets', true)
on conflict (id) do nothing;

-- ── 3 · policies ────────────────────────────────────────────────────────────
drop policy if exists profile_read on erph.user;
drop policy if exists member_read on erph.school_member;
drop policy if exists storage_read_school_logo on storage.objects;

create policy profile_read on erph.user
  for select using (
    id = erph.actor()
    or (erph.shares_school_with(erph.user.id) and erph.user.role <> 'pentadbir')
  );

create policy member_read on erph.school_member
  for select using (
    user_id = erph.actor()
    or (erph.is_staff(erph.school_member.school_id)
        and erph.school_member.role <> 'pentadbir')
  );

create policy storage_read_school_logo on storage.objects
  for select using (bucket_id = 'school-assets');

-- ── 4 · the administrator's editor ─────────────────────────────────────────
drop function if exists erph.admin_set_school(uuid, text, text, text, text, text);
create or replace function erph.admin_set_school(p_school uuid, p_kod_sekolah text,
                                                 p_nama text,
                                                 p_ppd text, p_jpn text,
                                                 p_motto text, p_logo_url text)
returns void language plpgsql security definer set search_path = erph, public as $$
declare
  v_kod   text := nullif(trim(p_kod_sekolah), '');
  v_rows  integer;
begin
  if not erph.has_role(p_school, array['pentadbir']::erph.member_role[]) then
    raise exception 'Peranan pentadbir diperlukan';
  end if;
  if v_kod is null then
    raise exception 'Kod sekolah diperlukan';
  end if;
  -- KPM codes are alphanumeric (BBA4039); the seed's SK0000 and a hyphen are
  -- allowed. Length is capped by the column's own use as a natural key rather
  -- than left to the form.
  if v_kod !~ '^[A-Za-z0-9][A-Za-z0-9._-]{2,23}$' then
    raise exception 'Kod sekolah 3-24 aksara: huruf, nombor, titik, - atau _ sahaja';
  end if;
  if nullif(trim(p_nama), '') is null then
    raise exception 'Nama sekolah diperlukan';
  end if;
  -- Only a path under our own origin or an explicit URL. A `javascript:` value
  -- stored here would be rendered as an image `src` across the app.
  if p_logo_url is not null and p_logo_url !~ '^(/|https?://)' then
    raise exception 'Logo mesti dalam bentuk URL yang sah';
  end if;

  begin
    update erph.school
       set kod_sekolah = v_kod,
           nama    = trim(p_nama),
           ppd     = nullif(trim(p_ppd), ''),
           jpn     = nullif(trim(p_jpn), ''),
           motto   = nullif(trim(p_motto), ''),
           logo_url = p_logo_url
     where id = p_school;
    -- Captured here rather than read as FOUND afterwards: the row-count lives
    -- inside a block whose whole purpose is to intercept an exception, and
    -- relying on FOUND to survive that boundary is a guess this file should
    -- not have to make.
    get diagnostics v_rows = row_count;
  exception when unique_violation then
    -- Never surfaces as Postgres' "duplicate key value … school_kod_sekolah_key":
    -- the API passes this text straight through to the form.
    raise exception 'Kod sekolah itu sudah digunakan';
  end;

  if v_rows = 0 then
    raise exception 'Sekolah tidak dijumpai';
  end if;
end $$;
