-- ============================================================================
-- eRPH · MIGRATION 003 — the school's own identity
-- ============================================================================
-- Run AFTER 001a/001b and 002. Safe to run more than once.
--
--   · erph.school gains `motto` and `logo_url` — what the administrator edits
--     from /pentadbiran and what the login screen, sidebar and printed RPH
--     then show everywhere.
--   · erph.admin_set_school writes them (pentadbir-only, checked in SQL).
--   · the public `school-assets` bucket the crest is served from.
--   · profile_read / member_read stop a GPK or Guru Besar reading the
--     Administrator's account through `shares_school_with` / `is_staff`.
--
-- Policies are dropped first: `create policy` has no `if exists`, and these
-- two would otherwise collide with the copies already installed.
--
-- Generated by scripts/gen-migration.py from db/schema.sql:
--
--   python scripts/gen-migration.py
--
-- ── 1 · columns ─────────────────────────────────────────────────────────────
alter table erph.school add column if not exists motto text;
alter table erph.school add column if not exists logo_url text;

-- ── 2 · the bucket the crest is served from ─────────────────────────────────
-- Public: the crest renders on the login screen before a session exists.
insert into storage.buckets (id, name, public) values
  ('rph-exports', 'rph-exports', false),
  ('attachments', 'attachments', false),
  -- Public: the school crest renders on the login screen before any session
  -- exists, and `next/image` fetches it server-side without a cookie.
  ('school-assets', 'school-assets', true)
on conflict (id) do nothing;

-- ── 3 · policies ────────────────────────────────────────────────────────────
drop policy if exists profile_read on erph.user;
drop policy if exists member_read on erph.school_member;
drop policy if exists storage_read_school_logo on storage.objects;

create policy profile_read on erph.user
  for select using (
    id = erph.actor()
    or (erph.shares_school_with(erph.user.id) and erph.user.role <> 'pentadbir')
  );

create policy member_read on erph.school_member
  for select using (
    user_id = erph.actor()
    or (erph.is_staff(erph.school_member.school_id)
        and erph.school_member.role <> 'pentadbir')
  );

create policy storage_read_school_logo on storage.objects
  for select using (bucket_id = 'school-assets');

-- ── 4 · the administrator's editor ─────────────────────────────────────────
create or replace function erph.admin_set_school(p_school uuid, p_nama text,
                                                 p_ppd text, p_jpn text,
                                                 p_motto text, p_logo_url text)
returns void language plpgsql security definer set search_path = erph, public as $$
begin
  if not erph.has_role(p_school, array['pentadbir']::erph.member_role[]) then
    raise exception 'Peranan pentadbir diperlukan';
  end if;
  if nullif(trim(p_nama), '') is null then
    raise exception 'Nama sekolah diperlukan';
  end if;
  -- Only a path under our own origin or an explicit URL. A `javascript:` value
  -- stored here would be rendered as an image `src` across the app.
  if p_logo_url is not null and p_logo_url !~ '^(/|https?://)' then
    raise exception 'Logo mesti dalam bentuk URL yang sah';
  end if;

  update erph.school
     set nama    = trim(p_nama),
         ppd     = nullif(trim(p_ppd), ''),
         jpn     = nullif(trim(p_jpn), ''),
         motto   = nullif(trim(p_motto), ''),
         logo_url = p_logo_url
   where id = p_school;

  if not found then
    raise exception 'Sekolah tidak dijumpai';
  end if;
end $$;
