-- ============================================================================
-- eRPH · MIGRATION 004 — supervision scope and the signed single-stage review
-- ============================================================================
-- Run AFTER 001a/001b/002/003. Safe to run more than once.
--
--   · erph.school_member gains `supervisor_id`, so a GPK's scope is the set of
--     teachers who point at them rather than every plan in the school.
--   · erph.semak_rph and erph.lulus_rph are retired. There is no longer a
--     GPK → Guru Besar hop: a GPK approves directly, and a Guru Besar can do
--     everything a GPK can on any teacher's plan.
--   · erph.rph_signature is new, and only the server can write to it —
--     approval is impossible without a signature already on file.
--
-- `forwarded` stays in the rph_status enum: Postgres cannot drop a value, and
-- nothing produces it any more.
--
-- Generated by scripts/gen-migration.py from db/schema.sql:
--
--   python scripts/gen-migration.py
--
-- ── 1 · supervision column ──────────────────────────────────────────────────
alter table erph.school_member
  add column if not exists supervisor_id uuid references erph.user(id) on delete set null;

create index if not exists school_member_school_role_idx on erph.school_member (school_id, role) where is_active;
create index if not exists school_member_supervisor_idx on erph.school_member (school_id, supervisor_id)
  where supervisor_id is not null;

-- ── 2 · retire the two-stage functions ──────────────────────────────────────
-- Dropped rather than replaced: a differently-shaped `create or replace` would
-- leave the old arity behind as a silent overload.
drop function if exists erph.semak_rph(uuid, smallint, text);
drop function if exists erph.lulus_rph(uuid, smallint, text);
-- Return type gained four columns, and Postgres refuses to change one in place.
drop function if exists erph.admin_list_members(uuid);

-- ── 3 · the new functions ───────────────────────────────────────────────────
-- Before any policy that mentions them: `create policy` resolves the function
-- references in its expression at creation time, so a policy written above
-- would fail with "function may_supervise does not exist".
create or replace function erph.supervises(p_school uuid, p_member uuid)
returns boolean language sql stable security definer set search_path = erph, public as $$
  select exists (
    select 1
      from erph.school_member t
     where t.school_id = p_school
       and t.user_id = p_member
       and t.is_active
       and t.supervisor_id = erph.actor()
  );
$$;

create or replace function erph.may_supervise(p_school uuid, p_owner uuid)
returns boolean language sql stable security definer set search_path = erph, public as $$
  select erph.actor() = p_owner
      or erph.has_role(p_school, array['guru_besar']::erph.member_role[])
      or erph.supervises(p_school, p_owner);
$$;

create or replace function erph.admin_set_supervisor(p_school uuid, p_member uuid,
                                                     p_supervisor uuid)
returns void language plpgsql security definer set search_path = erph, public as $$
begin
  if not erph.has_role(p_school, array['pentadbir']::erph.member_role[]) then
    raise exception 'Peranan pentadbir diperlukan';
  end if;
  if p_member = p_supervisor then
    raise exception 'Ahli tidak boleh menyelia diri sendiri';
  end if;
  if not exists (select 1 from erph.school_member
                  where school_id = p_school and user_id = p_member) then
    raise exception 'Bukan ahli sekolah ini';
  end if;
  if p_supervisor is not null then
    if not exists (select 1 from erph.school_member
                    where school_id = p_school and user_id = p_supervisor
                      and role in ('gpk','guru_besar') and is_active) then
      raise exception 'Penyelia mesti GPK atau Guru Besar yang aktif';
    end if;
  end if;

  update erph.school_member set supervisor_id = p_supervisor
   where school_id = p_school and user_id = p_member;

  -- Reassigning a supervisor orphans nothing, but a teacher moved from one GPK
  -- to another must not leave the previous GPK holding a plan they can no
  -- longer open. Nothing is rewritten — plans keep who signed them — only the
  -- *forward* scope changes, which is exactly what the UPDATE above does.
end $$;

create or replace function erph.admin_list_members(p_school uuid)
returns table (user_id uuid, username text, full_name text, email text,
               role erph.member_role, is_active boolean,
               last_login_at timestamptz, locked_until timestamptz,
               failed_logins int, password_changed_at timestamptz,
               supervisor_id uuid, supervisor_name text)
language sql stable security definer set search_path = erph, public as $$
  select m.user_id, u.username, u.full_name, u.email, m.role, u.is_active,
         u.last_login_at, u.locked_until, u.failed_logins, u.password_changed_at,
         m.supervisor_id, sup.full_name
    from erph.school_member m
    join erph.user u on u.id = m.user_id
    left join erph.user sup on sup.id = m.supervisor_id
   where m.school_id = p_school and erph.has_role(p_school, array['pentadbir']::erph.member_role[])
   order by m.role, u.username;
$$;

create or replace function erph.sahkan_rph(p_document uuid,
                                           p_comment text default null)
returns jsonb language plpgsql security definer set search_path = erph, public as $$
declare
  v_doc erph.rph_document%rowtype;
begin
  perform set_config('app.rpc', '1', true);

  select * into v_doc from erph.rph_document
   where id = p_document and deleted_at is null for update;
  if not found then raise exception 'RPH tidak dijumpai'; end if;

  if not erph.has_role(v_doc.school_id, array['gpk','guru_besar']::erph.member_role[]) then
    raise exception 'Peranan Guru Penolong Kanan atau Guru Besar diperlukan';
  end if;
  if not erph.may_supervise(v_doc.school_id, v_doc.owner_id) then
    raise exception 'RPH di luar bidang penyeliaan anda';
  end if;
  if v_doc.owner_id = erph.actor() then
    raise exception 'Anda tidak boleh mengesahkan RPH sendiri';
  end if;
  if v_doc.status <> 'submitted' then
    raise exception 'RPH tidak dalam peringkat semakan';
  end if;
  if not exists (select 1 from erph.rph_signature
                  where document_id = v_doc.id
                    and document_version = v_doc.version
                    and signer_id = erph.actor()) then
    raise exception 'Tandatangan diperlukan';
  end if;

  insert into erph.rph_review (document_id, document_version, reviewer_id, grade, comment, checklist)
  values (v_doc.id, v_doc.version, erph.actor(), 1, p_comment,
          jsonb_build_object('stage', 'sahkan',
                             'completeness', erph.rph_completeness(v_doc.payload)));

  update erph.rph_document
     set status = 'approved'::erph.rph_status,
         grade = 1, reviewed_by = erph.actor(), reviewed_at = now(),
         version = version + 1
   where id = p_document;

  insert into erph.notification (school_id, user_id, type, title, body, link_view)
  values (v_doc.school_id, v_doc.owner_id, 'approved'::erph.notification_type,
          'RPH disahkan', coalesce(p_comment, ''), 'dashboard');

  insert into erph.audit_log (school_id, actor_id, entity, entity_id, action, after)
  values (v_doc.school_id, erph.actor(), 'rph_document', v_doc.id, 'sahkan',
          jsonb_build_object('status', 'approved', 'comment', p_comment));

  return jsonb_build_object('ok', true, 'grade', 1, 'status', 'approved');
end $$;

create or replace function erph.hantar_balik_rph(p_document uuid,
                                                 p_comment text default null)
returns jsonb language plpgsql security definer set search_path = erph, public as $$
declare
  v_doc erph.rph_document%rowtype;
begin
  perform set_config('app.rpc', '1', true);

  select * into v_doc from erph.rph_document
   where id = p_document and deleted_at is null for update;
  if not found then raise exception 'RPH tidak dijumpai'; end if;

  if not erph.has_role(v_doc.school_id, array['gpk','guru_besar']::erph.member_role[]) then
    raise exception 'Peranan Guru Penolong Kanan atau Guru Besar diperlukan';
  end if;
  if not erph.may_supervise(v_doc.school_id, v_doc.owner_id) then
    raise exception 'RPH di luar bidang penyeliaan anda';
  end if;
  if v_doc.owner_id = erph.actor() then
    raise exception 'Anda tidak boleh mengembalikan RPH sendiri';
  end if;
  if v_doc.status <> 'submitted' then
    raise exception 'RPH tidak dalam peringkat semakan';
  end if;

  insert into erph.rph_review (document_id, document_version, reviewer_id, grade, comment, checklist)
  values (v_doc.id, v_doc.version, erph.actor(), 0, p_comment,
          jsonb_build_object('stage', 'hantar_balik',
                             'completeness', erph.rph_completeness(v_doc.payload)));

  update erph.rph_document
     set status = 'returned'::erph.rph_status,
         grade = 0, reviewed_by = erph.actor(), reviewed_at = now(),
         version = version + 1
   where id = p_document;

  insert into erph.notification (school_id, user_id, type, title, body, link_view)
  values (v_doc.school_id, v_doc.owner_id, 'returned'::erph.notification_type,
          'RPH perlu dibaiki', coalesce(p_comment, ''), 'dashboard');

  insert into erph.audit_log (school_id, actor_id, entity, entity_id, action, after)
  values (v_doc.school_id, erph.actor(), 'rph_document', v_doc.id, 'hantar_balik',
          jsonb_build_object('status', 'returned', 'comment', p_comment));

  return jsonb_build_object('ok', true, 'grade', 0, 'status', 'returned');
end $$;

-- ── 4 · the signature store ─────────────────────────────────────────────────
-- Deliberately has no INSERT or UPDATE policy. PostgreSQL cannot verify an
-- ECDSA signature (pgcrypto: "No support for signing"), so the database cannot
-- check one; instead it restricts who may append, and sahkan_rph refuses to
-- approve a plan without a matching row. See the comment on the table.
create table if not exists erph.rph_signature (
  id               bigint generated always as identity primary key,
  document_id      uuid not null references erph.rph_document(id) on delete cascade,
  document_version int not null,                          -- the version covered
  signer_id        uuid not null references erph.user(id),
  alg              text not null check (alg in ('ES256')),
  public_key       text not null,                        -- base64url SPKI/P-256
  signature        text not null,                        -- base64url, raw r||s
  envelope         jsonb not null,                       -- what was signed
  signed_at        timestamptz not null default now(),
  unique (document_id, document_version, signer_id)
);

create index if not exists rph_signature_signer_idx on erph.rph_signature (signer_id, signed_at desc);
alter table erph.rph_signature enable row level security;
drop policy if exists rph_signature_read on erph.rph_signature;
create policy rph_signature_read on erph.rph_signature
  for select using (exists (select 1 from erph.rph_document d
                            where d.id = erph.rph_signature.document_id
                              and erph.may_supervise(d.school_id, d.owner_id)));

-- ── 5 · scope-limited read policies ─────────────────────────────────────────
drop policy if exists rph_reviewer_read on erph.rph_document;
drop policy if exists rph_revision_read on erph.rph_revision;
drop policy if exists rph_review_read on erph.rph_review;

create policy rph_reviewer_read on erph.rph_document
  for select using (deleted_at is null and erph.may_supervise(school_id, owner_id));
create policy rph_revision_read on erph.rph_revision
  for select using (exists (select 1 from erph.rph_document d
                            where d.id = erph.rph_revision.document_id
                              and erph.may_supervise(d.school_id, d.owner_id)));
create policy rph_review_read on erph.rph_review
  for select using (exists (select 1 from erph.rph_document d
                            where d.id = erph.rph_review.document_id
                              and erph.may_supervise(d.school_id, d.owner_id)));