-- ============================================================================
-- eRPH · MIGRATION 006 — sign in with a KPM Google account
-- ============================================================================
-- Run AFTER 001a/001b/002/003/004/005. Safe to run more than once.
--
-- Two columns that bind an existing account to a Google identity. Nothing is
-- populated here: linking happens on a teacher's first successful Google
-- sign-in, and only for an account the pentadbir has already created. There is
-- deliberately no auto-provision — every teacher in the ministry has an
-- @moe-dl.edu.my address, so "create one if none exists" would let any of them
-- walk into this school's records by typing its URL.
--
-- Password login is unaffected. It remains the only route in local mode, and
-- the only route for anyone without an MOE account.
--
-- Generated by scripts/gen-migration.py from db/schema.sql:
--
--   python scripts/gen-migration.py
--
-- ── 1 · columns ─────────────────────────────────────────────────────────────
alter table erph.user add column if not exists google_sub text;
alter table erph.user add column if not exists google_email text;

-- A named constraint rather than a column-level `unique`, because the column
-- form would name it `user_google_sub_key` and dropping or replacing it later
-- would mean guessing what Postgres decided to call it.
alter table erph.user drop constraint if exists user_google_sub_uniq;
alter table erph.user add constraint user_google_sub_uniq unique (google_sub);
