-- ============================================================================
-- eRPH ▸ MIGRATION 007 — the school's own RPH template
-- ============================================================================
-- Run AFTER 001a/001b/002/003/004/005/006. Safe to run more than once.
--
-- Three things, all forced by matching the form the school actually submits:
--
--   1. `slot_time_end`. The printed form has Masa Mula *and* Masa Tamat, and a
--      plan that carries only a start time leaves the printed page to invent an
--      end time — which is how a five-hour lesson reaches an approved document.
--      Defaulted to 12:40, the school's own end time, so every existing plan
--      prints a plausible pair rather than a dash.
--
--   2. `rph_completeness` redefined. Kriteria Kejayaan replaces the old
--      Intervensi/EMK checkpoint: the printed form has a Kriteria Kejayaan row
--      and no Intervensi or EMK row, so scoring those meant a plan could read
--      100% while missing a field the district will look for — or read less
--      than 100% because a teacher left blank the content nobody prints.
--
--      Also: an activity now scores if *any* element carries a `nama`, not if
--      the first does. An activity list whose first row is a blank separator
--      still has activities in it, and a gate that cannot be satisfied by
--      filling the form correctly is a bug, not a check.
--
--   3. `sync_rph` widened to carry the new column. Without it, a plan edited
--      offline and synced back would keep whatever end time the server had.
--
-- The payload reshape itself (aktiviti → names, tajuk, kriteria_kejayaan) is
-- client-side and needs no DDL: zod strips what it does not know, so documents
-- written before this change stay readable, they simply carry less.
--
-- Generated by scripts/gen-migration.py from db/schema.sql:
--
--   python scripts/gen-migration.py
--
-- ▸ 1 ▸ the column ──────────────────────────────────────────────────────────
alter table erph.rph_document
  add column if not exists slot_time_end time not null default '12:40';

-- ▸ 2 ▸ the completeness rules ──────────────────────────────────────────────
create or replace function erph.rph_completeness(p_payload jsonb)
returns smallint language plpgsql immutable as $$
declare
  v int := 0;
  v_act jsonb := coalesce(p_payload->'aktiviti', '[]'::jsonb);
begin
  -- 1. Standard Kandungan + Standard Pembelajaran
  if nullif(trim(coalesce(p_payload->>'standard_kandungan','')), '') is not null
     and nullif(trim(coalesce(p_payload->>'standard_pembelajaran','')), '') is not null
  then v := v + 25; end if;

  -- 2. Objektif + Kriteria Kejayaan
  if nullif(trim(coalesce(p_payload->>'objektif','')), '') is not null
     and nullif(trim(coalesce(p_payload->>'kriteria_kejayaan','')), '') is not null
  then v := v + 25; end if;

  -- 3. at least one Aktiviti PdPC carrying a name. `exists` over the array
  -- rather than a check on element 0: an activity list whose first entry is a
  -- blank separator line is not an empty list, and refusing to submit over it
  -- would be a gate that cannot be satisfied by filling the form correctly.
  if jsonb_typeof(v_act) = 'array' and exists (
       select 1 from jsonb_array_elements(v_act) e
        where nullif(trim(coalesce(e->>'nama','')), '') is not null)
  then v := v + 25; end if;

  -- 4. Refleksi
  if nullif(trim(coalesce(p_payload->>'refleksi','')), '') is not null
  then v := v + 25; end if;

  return v::smallint;
end $$;

-- ▸ 3 ▸ the sync function that carries the column ───────────────────────────
create or replace function erph.sync_rph(p_ops jsonb)
returns jsonb language plpgsql security definer set search_path = erph, public as $$
declare
  v_op jsonb; v_op_id uuid; v_id uuid; v_uid uuid := erph.actor();
  v_school uuid; v_doc_id uuid; v_ver int; v_status erph.rph_status;
  v_rows int; v_pct smallint; v_client_ts timestamptz;
  v_out jsonb := '[]'::jsonb;
begin
  if v_uid is null then raise exception 'Belum log masuk'; end if;
  perform set_config('app.rpc', '1', true);

  -- resolve caller's school once (all ops must belong to it)
  select school_id into v_school
    from erph.school_member where user_id = v_uid and is_active
   order by invited_at limit 1;
  if v_school is null then raise exception 'Tiada keahlian sekolah aktif'; end if;

  for v_op in select * from jsonb_array_elements(p_ops) loop
    v_op_id := (v_op->>'op_id')::uuid;
    v_id    := coalesce((v_op->>'id')::uuid, gen_random_uuid());
    v_pct    := erph.rph_completeness(v_op->'payload');
    v_client_ts := coalesce((v_op->>'client_updated_at')::timestamptz, now());

    -- 1) idempotency: replayed ops are no-ops
    insert into erph.sync_op (op_id, user_id, entity, entity_id)
    values (v_op_id, v_uid, 'rph', v_id)
    on conflict (op_id) do nothing;
    get diagnostics v_rows = row_count;
    if v_rows = 0 then
      v_out := v_out || jsonb_build_array(
        jsonb_build_object('op_id', v_op_id, 'result', 'duplicate'));
      continue;
    end if;

    -- 2) validate target class belongs to caller's school + session
    if not exists (
         select 1 from erph.class c
          where c.id = (v_op->>'class_id')::uuid
            and c.school_id = v_school and c.session = v_op->>'session' and c.is_active)
    then
      v_out := v_out || jsonb_build_array(
        jsonb_build_object('op_id', v_op_id, 'result', 'rejected',
                           'error', 'kelas bukan dalam sekolah/sesi anda'));
      continue;
    end if;
    if not exists (select 1 from erph.subject where code = v_op->>'subject_code') then
      v_out := v_out || jsonb_build_array(
        jsonb_build_object('op_id', v_op_id, 'result', 'rejected',
                           'error', 'mata pelajaran tidak dikenali'));
      continue;
    end if;

    -- 3) resolve canonical row: by id, else by natural key (merge duplicates)
    select id, version, status into v_doc_id, v_ver, v_status
      from erph.rph_document
     where owner_id = v_uid and deleted_at is null
       and (id = v_id
            or (class_id = (v_op->>'class_id')::uuid
                and subject_code = v_op->>'subject_code'
                and session = v_op->>'session'
                and week_no = (v_op->>'week_no')::smallint
                and plan_date = (v_op->>'plan_date')::date))
     order by (id = v_id) desc
     limit 1;

    if v_doc_id is not null then
      update erph.rph_document
         set payload = v_op->'payload',
             version = version + 1,
             client_updated_at = v_client_ts,
             slot_time = coalesce((v_op->>'slot_time')::time, slot_time),
             slot_time_end = coalesce((v_op->>'slot_time_end')::time, slot_time_end),
             content_hash = coalesce(v_op->>'content_hash', content_hash),
             -- Status is server-managed. The client may request only:
             --   • nothing (null)     → keep current state
             --   • 'submitted'        → allowed ONLY when 100% complete
             -- Everything else (including leaving approved/returned) is dropped,
             -- so sync can never bypass submit_rph()'s completeness gate or
             -- let a teacher self-approve their own plan.
             status = case
                        when v_op->>'status' is null then status
                        when status in ('approved', 'returned')
                             and v_op->>'status' <> 'submitted' then status
                        when v_op->>'status' = 'submitted' and v_pct = 100
                          then 'submitted'::erph.rph_status
                        when v_op->>'status' = 'submitted' then status
                        else 'draft'::erph.rph_status
                      end,
             submitted_at = case when v_op->>'status' = 'submitted' and v_pct = 100
                                 and submitted_at is null
                                 then now() else submitted_at end
       where id = v_doc_id and owner_id = v_uid
      returning version, status into v_ver, v_status;
    else
      begin
        insert into erph.rph_document
          (id, school_id, owner_id, class_id, subject_code, session, week_no, plan_date,
           slot_time, slot_time_end, payload, status, version, client_updated_at, content_hash, submitted_at)
        values
          (v_id, v_school, v_uid, (v_op->>'class_id')::uuid, v_op->>'subject_code',
           v_op->>'session', (v_op->>'week_no')::smallint, (v_op->>'plan_date')::date,
           coalesce((v_op->>'slot_time')::time, '07:30'::time),
           coalesce((v_op->>'slot_time_end')::time, '12:40'::time),
           v_op->'payload',
           -- New documents are always drafts: submitting is an explicit act
           -- through submit_rph(), and the same 100% gate applies here.
           case when v_op->>'status' = 'submitted' and v_pct = 100
                then 'submitted'::erph.rph_status
                else 'draft'::erph.rph_status end,
           1, v_client_ts, v_op->>'content_hash',
           case when v_op->>'status' = 'submitted' and v_pct = 100 then now() end)
        returning id, version, status into v_doc_id, v_ver, v_status;
      exception when unique_violation then
        -- race: another request created the same logical plan → merge into it
        update erph.rph_document
           set payload = v_op->'payload',
               version = version + 1,
               client_updated_at = v_client_ts,
               slot_time = coalesce((v_op->>'slot_time')::time, slot_time),
               slot_time_end = coalesce((v_op->>'slot_time_end')::time, slot_time_end)
         where owner_id = v_uid
           and class_id = (v_op->>'class_id')::uuid
           and subject_code = v_op->>'subject_code'
           and session = v_op->>'session'
           and week_no = (v_op->>'week_no')::smallint
           and plan_date = (v_op->>'plan_date')::date
           and deleted_at is null
        returning id, version, status into v_doc_id, v_ver, v_status;
      end;
    end if;

    if v_doc_id is null then
      v_out := v_out || jsonb_build_array(
        jsonb_build_object('op_id', v_op_id, 'result', 'rejected',
                           'error', 'tidak dapat menentukan dokumen'));
      continue;
    end if;

    insert into erph.rph_revision (document_id, version, payload, completeness, actor_id, reason)
    values (v_doc_id, v_ver, v_op->'payload', v_pct, v_uid, 'sync')
    on conflict (document_id, version) do nothing;

    update erph.sync_op set result = jsonb_build_object('id', v_doc_id, 'version', v_ver)
     where op_id = v_op_id;

    v_out := v_out || jsonb_build_array(jsonb_build_object(
      'op_id', v_op_id, 'result', 'applied', 'id', v_doc_id,
      'version', v_ver, 'status', v_status, 'completeness', v_pct));
  end loop;

  return v_out;
end $$;
