import type { MemberRole } from "@/lib/types";

/**
 * Accounts used when Supabase is not configured (offline/local mode).
 *
 * There is no database to look a user up in, so they live here — but the
 * password still goes through the *same* scrypt verification as a real
 * account, so local mode exercises the real code path rather than a shortcut.
 *
 * Two of them, deliberately: with a single superuser, role separation can be
 * neither demonstrated nor tested. The demo account is a Guru Besar so every
 * screen stays reachable for a walkthrough; the second is an ordinary teacher,
 * used to prove the gates actually bite.
 *
 *   cikgu       / cikgu123  → Guru Besar   (review, monitoring, reports)
 *   guru.biasa  / biasa123  → Guru Biasa   (own RPH only)
 *
 * `password_changed_at` is epoch 0 so any session cookie is accepted (there is
 * nothing to invalidate against).
 */
export interface LocalAccount {
  id: string;
  username: string;
  password_hash: string;
  role: MemberRole;
  full_name: string;
  email: string | null;
}

const GURU_BESAR: LocalAccount = {
  id: "00000000-0000-4000-8000-000000000001",
  username: "cikgu",
  // scrypt(16384,8,1) of LOCAL_DEMO_PASSWORD — generated by
  // scripts/hash-password.js. The verification path is identical to a real
  // account; only the storage location differs.
  password_hash:
    "scrypt$16384$8$1$eNeYGEYGseBchq2cCkdbEw$_HcR2qoDKwgZK7FsRa5ZSnEOmp79n_-xhk6svmnyCej_QIXc3XhEo2hdRcOtN1L_nZEVo61LV9_GoXHJmRtDeA",
  role: "guru_besar",
  full_name: "Nurul Aisyah binti Rahim",
  email: "nurul@sktamanharmoni.local",
};

const GURU_BIASA: LocalAccount = {
  id: "00000000-0000-4000-8000-000000000002",
  username: "guru.biasa",
  password_hash:
    "scrypt$16384$8$1$l5LNcBYQOSm6M_tOuRNTyw$OIhgfFgcxiGTo2GeOra-dmMfOc8KlQeHl1szR9cN9UlvxU_lB86lLYutFhYlCM1Axphko8kuo3qvqJQxaG135g",
  role: "guru_biasa",
  full_name: "Suhaila binti Hassan",
  email: "suhaila@sktamanharmoni.local",
};

export const LOCAL_ACCOUNTS: readonly LocalAccount[] = [GURU_BESAR, GURU_BIASA];

/** The account the login screen names in local mode. */
export const LOCAL_ACCOUNT: LocalAccount = GURU_BESAR;

export const localAccountById = (id: string): LocalAccount | undefined =>
  LOCAL_ACCOUNTS.find((a) => a.id === id);

export const localAccountByUsername = (username: string): LocalAccount | undefined =>
  LOCAL_ACCOUNTS.find((a) => a.username === username);

/**
 * The demo password, shown on the login screen **only in local mode**.
 *
 * This is not a secret: there is no database, no remote, and the mode exists
 * so the product can be demoed offline. The moment Supabase is configured,
 * this constant is unreachable — login reads `erph.user` instead.
 */
export const LOCAL_DEMO_PASSWORD = "cikgu123";
