/**
 * The demo account used when Supabase is not configured (offline/local mode).
 *
 * There is no database to look a user up in, so the account lives here — but
 * the password still goes through the *same* scrypt verification as a real
 * account, so local mode exercises the real code path rather than a shortcut.
 *
 *   username: cikgu
 *   password: cikgu123
 *
 * `password_changed_at` is epoch 0 so any session cookie is accepted (there is
 * nothing to invalidate against).
 */
export const LOCAL_ACCOUNT = {
  id: "00000000-0000-4000-8000-000000000001",
  username: "cikgu",
  // scrypt(16384,8,1) of LOCAL_DEMO_PASSWORD — generated by
  // scripts/hash-password.js. The verification path is identical to a real
  // account; only the storage location differs.
  password_hash:
    "scrypt$16384$8$1$eNeYGEYGseBchq2cCkdbEw$_HcR2qoDKwgZK7FsRa5ZSnEOmp79n_-xhk6svmnyCej_QIXc3XhEo2hdRcOtN1L_nZEVo61LV9_GoXHJmRtDeA",
  role: "admin" as const, // so every screen (incl. review/monitoring) is reachable
  full_name: "Nurul Aisyah binti Rahim",
  email: "nurul@sktamanharini.local",
};

/**
 * The demo password, shown on the login screen **only in local mode**.
 *
 * This is not a secret: there is no database, no remote, and the mode exists
 * so the product can be demoed offline. The moment Supabase is configured,
 * this constant is unreachable — login reads `erph.user` instead.
 */
export const LOCAL_DEMO_PASSWORD = "cikgu123";
