"""Emit db/migrations/001_roles_and_two_stage.sql from db/schema.sql.

The schema file is not idempotent (create type / create table / create policy),
so an existing project cannot simply re-run it. This pulls the *definitions
that changed* straight out of schema.sql — never hand-copied — and wraps them
in the DDL an existing database needs.

    python scripts/gen-migration.py
"""
import pathlib
import re

root = pathlib.Path(__file__).resolve().parent.parent
sql = (root / "db" / "schema.sql").read_text(encoding="utf-8")

FUNCTIONS = [
    "is_staff",
    "shares_school_with",
    "submit_rph",
    "semak_rph",
    "lulus_rph",
    "school_week_stats",
    "admin_list_members",
    "admin_set_member",
    "admin_set_setting",
]

# Policies that embed a role literal. After the rename the old literals do not
# exist, so evaluating one of these would raise rather than merely deny.
POLICIES = [
    ("rph_reviewer_read", "erph.rph_document"),
    ("rph_revision_read", "erph.rph_revision"),
    ("rph_review_read", "erph.rph_review"),
    ("export_read", "erph.export_file"),
    ("audit_admin_read", "erph.audit_log"),
    ("storage_read", "storage.objects"),
]

VIEWS = ["v_teacher_week", "v_school_compliance"]


def function(name: str) -> str:
    # The body is `as $$ … $$;` for SQL functions and `as $$ … end $$;` for
    # plpgsql; either way `$$;` appears exactly twice and the first one is the
    # terminator.
    m = re.search(rf"create or replace function erph\.{re.escape(name)}\(.*?\$\$;", sql, re.S)
    if not m:
        raise SystemExit(f"function erph.{name} not found in db/schema.sql")
    return m.group(0)


def policy(name: str) -> str:
    m = re.search(rf"create policy {re.escape(name)} on [\s\S]*?;", sql)
    if not m:
        raise SystemExit(f"policy {name} not found in db/schema.sql")
    return m.group(0)


def view(name: str) -> str:
    """Extract a view definition, stopping at the first real terminator.

    A comment inside the body can contain a semicolon (`-- Guru Besar;`), so a
    regex up to `;` truncates the statement mid-flight.
    """
    m = re.search(rf"create view erph\.{re.escape(name)}", sql)
    if not m:
        raise SystemExit(f"view erph.{name} not found in db/schema.sql")
    out = [sql[m.start() :].splitlines()[0]]
    for ln in sql[m.start() :].splitlines()[1:]:
        if ln.strip().startswith("--"):
            continue
        out.append(ln)
        if ln.strip().endswith(";"):
            break
    return "\n".join(out)


DIR = root / "db" / "migrations"
DIR.mkdir(parents=True, exist_ok=True)

# ── A: the ALTER TYPE statements, deliberately alone ──────────────────────────
# These cannot ride along with the rest, so they get their own file: pasting
# the whole migration at once is exactly the mistake this split prevents.
alter_a = DIR / "001a_alter_types.sql"
alter_a.write_text(
    """-- ============================================================================
-- eRPH · MIGRATION 001a — role and status values (RUN ONE LINE AT A TIME)
-- ============================================================================
-- Run BEFORE 001b_schema_delta.sql, and run it by selecting a single line and
-- pressing Run each time. Two Postgres rules make that unavoidable:
--
--   · `alter type ... rename value` refuses to run inside a transaction block,
--     and the SQL editor wraps a pasted script in one.
--   · a value added inside a transaction cannot be used until it commits —
--     001b defines functions that reference `pentadbir` and views that
--     reference `forwarded`, so both must exist before it starts.
--
-- Six lines. Each should report "ALTER TYPE".
-- ============================================================================

alter type erph.member_role rename value 'teacher'     to 'guru_biasa';
alter type erph.member_role rename value 'coordinator' to 'gpk';
alter type erph.member_role rename value 'admin'       to 'guru_besar';
alter type erph.member_role add value if not exists 'pentadbir';
alter type erph.rph_status add value if not exists 'forwarded';
alter type erph.notification_type add value if not exists 'forwarded';
""",
    encoding="utf-8",
)

OUT = DIR / "001b_schema_delta.sql"

body = f"""-- ============================================================================
-- eRPH · MIGRATION 001b — the schema delta (paste this whole file)
-- ============================================================================
-- Run AFTER 001a_alter_types.sql, which must be run one line at a time.
--
-- For a Supabase project created before commit e46e870. A fresh install needs
-- none of this: db/schema.sql already describes the end state.
--
-- Generated by scripts/gen-migration.py from db/schema.sql, so the definitions
-- below cannot drift from the schema they are migrating towards.
--
--   python scripts/gen-migration.py
-- ============================================================================

-- ── 1 · column defaults ────────────────────────────────────────────────────
alter table erph.user         alter column role set default 'guru_biasa';
alter table erph.school_member alter column role set default 'guru_biasa';

-- ── 2 · the single-stage reviewer is gone ──────────────────────────────────
drop function if exists erph.review_rph(uuid, smallint, text);

-- ── 3 · helpers, RPCs and the new admin set-up ─────────────────────────────
{chr(10).join(chr(10) + function(n) + chr(10) for n in FUNCTIONS)}
-- ── 4 · policies embedding a role literal ─────────────────────────────────
drop policy if exists rph_reviewer_read on erph.rph_document;
drop policy if exists rph_revision_read on erph.rph_revision;
drop policy if exists rph_review_read on erph.rph_review;
drop policy if exists export_read on erph.export_file;
drop policy if exists audit_admin_read on erph.audit_log;
drop policy if exists storage_read on storage.objects;

{chr(10).join(policy(n) + chr(10) for n, _ in POLICIES)}
-- ── 5 · views (keyed on status, so a GPK's grade-1 is not an approval) ─────
drop view if exists erph.v_teacher_week;
drop view if exists erph.v_school_compliance;

{chr(10).join(view(n) + chr(10) for n in VIEWS)}
-- ── 6 · accounts ───────────────────────────────────────────────────────────
-- The district/state roles are gone from the app. Postgres cannot drop an enum
-- value at all, so deleting the rows is what keeps the data honest — leaving
-- them would mean two roles nothing references.
-- If those accounts ever produced an export, delete its export_file rows first.
delete from erph.school_member where user_id in
  (select id from erph.user where username in ('ppd.petaling', 'jpn.selangor'));
delete from erph.user where username in ('ppd.petaling', 'jpn.selangor');

-- ── 7 · the Administrator account ──────────────────────────────────────────
-- From db/seed.sql; change the password hash before any real deployment.
insert into erph.user (username, password_hash, full_name, email, role, is_active)
values ('pentadbir.sk',
        'scrypt$16384$8$1$sBZJbXJZGtDoXYVtM_r_MA$_Q_vvOJhHbPEbvKonOnd-ktpbXbn0axcvfihN6Gvw3QbzfzfEWoXvyhHi8rFcWaxKqNtYn9iUxIlQYOTgGmVGg',
        'Pentadbir eRPH', 'pentadbir@sk0000.local', 'pentadbir', true)
on conflict do nothing;

insert into erph.school_member (school_id, user_id, role)
select s.id, u.id, 'pentadbir' from erph.school s, erph.user u
where s.kod_sekolah = 'SK0000' and u.username = 'pentadbir.sk'
on conflict do nothing;
"""

OUT.write_text(body, encoding="utf-8")
print(f"{alter_a.relative_to(root)} written (6 statements, run one at a time)")
print(f"{OUT.relative_to(root)} written ({len(body)} chars)")
